AllCops:
  Exclude:
    - 'tasks/*.rake'
    - 'Rakefile'
    - 'db/schema.rb'
    - 'Gemfile*'
  TargetRubyVersion: 2.7.0

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

