version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - '3000:3000'
    depends_on:
      - database
    # environment:
      # DATABASE_URI: postgres://postgres:secret@database/
